import { Router } from 'express';
import { requireAuth } from '../middleware/auth.middleware';
import { validate } from '../middleware/validate.middleware';
import { createProjectSchema, connectRepoSchema } from '../schemas/project.schemas';
import * as ctrl from '../controllers/projects.controller';
const router = Router();
router.use(requireAuth);
router.get('/', ctrl.listProjects);
router.get('/:id', ctrl.getProject);
router.post('/', validate(createProjectSchema), ctrl.createProject);
router.delete('/:id', ctrl.archiveProject);
router.post('/:id/repos', validate(connectRepoSchema), ctrl.connectRepo);
export default router;
