package com.aria.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "concept_nodes",
        indexes = {
                @Index(name = "idx_concept_nodes_project", columnList = "project_id"),
                @Index(name = "idx_concept_nodes_type", columnList = "node_type")
        })
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ConceptNode {

    @Id
    @Column(nullable = false, updatable = false)
    private String id;

    @Column(name = "project_id", nullable = false)
    private String projectId;

    @Column(name = "workspace_id", nullable = false)
    private String workspaceId;

    /**
     * file | module | service | endpoint | db_table | function | class | interface
     */
    @Column(name = "node_type", nullable = false)
    private String nodeType;

    @Column(nullable = false)
    private String name;

    /** File path relative to repo root, e.g. src/main/java/com/aria/service/AuthService.java */
    @Column(name = "file_path")
    private String filePath;

    /** Raw summary generated by analysis engine (stubbed until Sprint 3) */
    @Column(columnDefinition = "TEXT")
    private String summary;

    /** JSON blob for any extra metadata the analysis engine attaches */
    @Column(name = "metadata", columnDefinition = "TEXT")
    private String metadata;

    @OneToMany(mappedBy = "sourceNode", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @Builder.Default
    private List<ConceptEdge> outgoingEdges = new ArrayList<>();

    @OneToMany(mappedBy = "targetNode", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @Builder.Default
    private List<ConceptEdge> incomingEdges = new ArrayList<>();

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;
}
